apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oci-mintmelon-tls
  namespace: resume-app
spec:
  secretName: tls-secret
  issuerRef:
    name: self-signed-issuer
    kind: ClusterIssuer
  dnsNames:
    - oci.mintmelon.ca
  duration: 8760h # 1 year
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - server auth
    - client auth 