name: Construct EC2

on:
  workflow_dispatch:  

env:  
  AWS_REGION: us-east-2

jobs:
  terraform:
    name: Apply Terraform configuration
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
          aws-region: ${{ env.AWS_REGION }} 

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

      - name: Save Terraform Outputs
        run: terraform output -raw instance_public_ip > ec2_ip.txt
      
      - name: Set GitHub Environment Variable
        run: echo "EC2_PUBLIC_IP=$(cat ec2_ip.txt)" >> $GITHUB_ENV
