name: Construct EC2

on:
  workflow_dispatch:  

env:  
  AWS_REGION: us-east-2

jobs:
  terraform:
    name: Apply Terraform configuration
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
          aws-region: ${{ env.AWS_REGION }} 

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
      
      - name: Get EC2 IP
        run: 
          terraform output -raw instance_public_ip > ip.txt
  
  build-image:
    name: AWS ECR preparation
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deploy to AWS ECR
        uses: BushLay/resume-modifier-frontend/.github/workflows/push_to_ecr.yml@main
        with: 
          VITE_SERVER_HOST: "http://$(cat ip.txt)"

      