name: Deploy to EC2

on:
  workflow_dispatch:
# Define environment variables  
env:  
  AWS_REGION: us-east-2
  UPDATE_SCRIPT: .github/workflows/ec2_update.sh


jobs:
  deploy:
    name: Deploy Docker Images to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Create Private Key File
      run: |
        which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )
        eval $(ssh-agent -s)
        echo "${{vars.AWS_SSH_PRIVATE_KEY}}" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        touch ~/.ssh/config
        touch ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        ssh-keyscan 3.138.124.182 >> ~/.ssh/known_hosts
    
    - name: Transfer Files to EC2
      run: |
        # Use SCP to copy the script to the EC2 instance
        scp -o StrictHostKeyChecking=no -r ${{ env.UPDATE_SCRIPT }} ec2-user@3.138.124.182:/home/ec2-user/
    
    - name: Run Deploy Script on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@3.138.124.182 << 'EOF'
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          chmod +x /home/ec2-user/ec2_update.sh
          /home/ec2-user/ec2_update.sh
        EOF
          
